server {
    listen 8080;
    root /usr/share/nginx/html;
    index index.html;

    location / {
        try_files $uri $uri/ /index.html;
    }

    location ~* \.(js|css|wasm)$ {
        expires 30d;
        add_header Cache-Control "public, immutable";
    }

    location ~* \.(png|wav|p|frag|vert)$ {
        expires 1h;
        add_header Cache-Control "public";
    }
}
